apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubeissuer
  namespace: {{ .Values.namespace.name }}
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: sivaneni1992@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: kubeissuer
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubecert
  namespace: {{ .Values.namespace.name }}
spec:
  secretName: bankapp-tls-secret
  issuerRef:
    name: kubeissuer
    kind: ClusterIssuer
  commonName: www.hitservicelab.xyz
  dnsNames:
  - www.hitservicelab.xyz